### ISSUE TITLE
UnknownDslObject: DSL class `instance` does not exist in query

### ISSUE THREAD

**Issue by murphyalexandre** [elastic/elasticsearch-dsl-py#1020]
Hi,

I'm not sure if this is a result of a bug fix, but running the latest version I have a weird bug that I didn't have before when trying to *add* two queries.

Context: I have a filter that groups 2 variables together so they can be filtered together with an *and*. Both these variables can have an *any* flag that doesn't filter the field. So the code looks a bit like this:

``
f = MatchNone()
rf = self.facets['first'].add_filter([first_filter]) if first_filter.lower() != 'any' else MatchAll()
tf = self.facets['second'].add_filter([second_filter]) if second_filter.lower() != 'any' else MatchAll()

 rf &= tf
 f |= rf

 self._filters['rights'] = f
``

I should mention that the `second` field is a nested facet and the problem arises on `rf &= tf` where it tries to get the class of the query, but fails since it's an instance at that time, and not a class name.

Full error log:
``
Internal Server Error: /some-route
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  ...
  File "/indexes.py", line 407, in some_method
    rf &= tf
  File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/query.py", line 60, in __and__
    return Bool(must=[self, other])
  File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 225, in __init__
    self._setattr(pname, pvalue)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 264, in _setattr
    value = list(map(shortcut, value))
  File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/query.py", line 31, in Q
    return Query.get_dsl_class(name_or_query)(**params)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 218, in get_dsl_class
    raise UnknownDslObject('DSL class `%s` does not exist in %s.' % (name, cls._type_name))
UnknownDslObject: DSL class `Nested(path=u'first', query=Bool(must=[Match(first__second=u'Some Value')]))` does not exist in query.
``

Any help would be appreciated.

**Comment by murphyalexandre** [comment]
Never mind, I fixed it somehow by fixing my subclass of `NestedFacet`. Still don't know what happened since this worked for some time.
