### ISSUE TITLE
elasticsearch.exceptions.SerializationError

### ISSUE THREAD

**Issue by naarkhoo** [elastic/elasticsearch-dsl-py#1062]
I get serialisation error, and I suspect it is due to the scrolling ... I wonder if there is any argument I am missing ...

```
from datetime import datetime
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import elasticsearch

client = elasticsearch.Elasticsearch('http://distribution.virk.dk:80',
                                          timeout=300)
from_date = datetime(2011, 1, 1)
s = Search(using=client, index='offentliggoerelser')
s = s.filter('range', offentliggoerelsesTidspunkt={'gte': from_date})
s = s.sort('offentliggoerelsesTidspunkt')
cnt = 0
for cnt, document in enumerate(s.scan()):
    erst_id = document.meta.id
    cvrnummer = document['cvrNummer']
    
    print("iteraction {0} CVR: {1}".format(cnt, cvrnummer))

    if cnt > 5:
        break
```

here is the error ...

```
Exception ignored in: <generator object scan at 0x11034ddb0>
Traceback (most recent call last):
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 403, in scan
    client.clear_scroll(body={'scroll_id': [scroll_id]}, ignore=(404, ))
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1037, in clear_scroll
    params=params, body=body)
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/elasticsearch/transport.py", line 349, in perform_request
    data = self.deserializer.loads(data, headers_response.get('content-type'))
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/elasticsearch/serializer.py", line 82, in loads
    raise SerializationError('Unknown mimetype, unable to deserialize: %s' % mimetype)
elasticsearch.exceptions.SerializationError: Unknown mimetype, unable to deserialize: text/html
```

**Comment by naarkhoo** [comment]
the reason I stop the process by `cnt>5` in fact, I get results ! meaning I hit the Elasticsearch - but at the end - I get the error ! I don't mind to share you the user/pass somewhere else !

**Comment by HonzaKral** [comment]
What is happening is you are getting a response with content type `text/html`, that is not a response from elasticsearch. You have `nginx` before elasticsearch on that url, getting an error reponse from `nginx` would definitely account for it, or there is something else wrong but it is definitely not in the client library. I am sorry I cannot be of more help
