### ISSUE TITLE
auto_date_histogram aggregation does not exist

### ISSUE THREAD

**Issue by stopmachine** [elastic/elasticsearch-dsl-py#1105]
To reproduce, simply:
```python
Search.from_dict({'aggs': {'by_date': {'auto_date_histogram': {'field': 'timestamp', 'buckets': 5}}}})
```

Which gives:
```python
Traceback (most recent call last):
  File "/home/yigal/workspace/pairsonal/enduser-data/src/api/fleet/users.py", line 124, in <module>
    elasticsearch_dsl.Search.from_dict({'aggs': {'by_date': {'auto_date_histogram': {'field': 'timestamp', 'bucets': 5}}}})
  File "/home/yigal/workspace/.venv/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 359, in from_dict
    s.update_from_dict(d)
  File "/home/yigal/workspace/.venv/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 409, in update_from_dict
    (name, A(value)) for (name, value) in iteritems(aggs))
  File "/home/yigal/workspace/.venv/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 409, in <genexpr>
    (name, A(value)) for (name, value) in iteritems(aggs))
  File "/home/yigal/workspace/.venv/lib/python3.6/site-packages/elasticsearch_dsl/aggs.py", line 33, in A
    return Agg.get_dsl_class(agg_type)(_expand__to_dot=False, **params)
  File "/home/yigal/workspace/.venv/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 216, in get_dsl_class
    raise UnknownDslObject('DSL class `%s` does not exist in %s.' % (name, cls._type_name))
elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `auto_date_histogram` does not exist in agg.
```

**Comment by HonzaKral** [comment]
thank you, we will add this soon. In the mean time you can always define the aggregation in your code as a workaround, just do:
```python
from elasticsearch_dsl.aggs import DateHistogram
class AutoDateHistogram(DateHistogram):
    name = 'auto_date_histogram'
```

and it will work.

Apologies for the inconvenience!
