### ISSUE TITLE
Nested Class with a Method Can't be Pickled

### ISSUE THREAD

**Issue by annawinkler** [elastic/elasticsearch-dsl-py#1109]
I have an example of the issue in this repository: https://github.com/annawinkler/es_address_book

To invoke the test, call `python pickle_test.py`.

Here is the output on my system with python 3.7:

```
(es-address-book) es_address_book(master)$ python pickle_test.py
House number 1023 street name Main Street city name Anytown
Traceback (most recent call last):
  File "/Users/awinkler/virtualenvs/es-address-book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 127, in __getattr__
    return self.__getitem__(attr_name)
  File "/Users/awinkler/virtualenvs/es-address-book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 140, in __getitem__
    return _wrap(self._d_[key])
KeyError: 'validate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pickle_test.py", line 37, in <module>
    main()
  File "pickle_test.py", line 26, in main
    out.validate()
  File "/Users/awinkler/dev/es_address_book/models.py", line 29, in validate
    [address_part.validate() for address_part in self.address]
  File "/Users/awinkler/dev/es_address_book/models.py", line 29, in <listcomp>
    [address_part.validate() for address_part in self.address]
  File "/Users/awinkler/virtualenvs/es-address-book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 130, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
AttributeError: 'AttrDict' object has no attribute 'validate'
```

Is there any way around this issue?

Thanks,
Anna

**Comment by HonzaKral** [comment]
Thank you for the report and apologies in the delay!
