### ISSUE TITLE
Creating an index with settings causes exceptions

### ISSUE THREAD

**Issue by ChaosCA** [elastic/elasticsearch-dsl-py#1163]
If you create a new index using the DSL that has settings in it's `class Index` you will receive errors from elasticsearch as the index has already been created.

```
PUT http://localhost:9200/logs_v6 [status:400 request:0.009s]
[2019-04-17 08:26:22 +0000] [21614] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/var/www/proj/owl_ucp/wsgi.py", line 18, in <module>
    application = get_wsgi_application()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/pyenv/versions/3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/www/proj/logs/models.py", line 165, in <module>
    Log.init()
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 138, in init
    i.save(using=using)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 284, in save
    return self.create(using=using)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 268, in create
    self._get_connection(using).indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 88, in create
    params=params, body=body)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/pyenv/versions/3.6.0/envs/proj/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'resource_already_exists_exception', 'index [logs_v6/uAD6iIZlRU6DMvHmEoI6WA] already exists')
```

This is will a sample index like so:
```
class Log(Document):
    date = Date()
    action = Integer()

    class Index:
        name = 'logs'
        doc_type = 'doc'
        settings = {
            'number_of_replicas': 0
        }
```

Then run:
`Log.init()`

**Comment by HonzaKral** [comment]
The problem is that the index already exists in elasticsearch so you cannot create it. This is not due to the library or anything, it is just due to the fact that in your cluster this index already exists.

It looks like I am missing some info so please feel to reopen the issue if this is indeed so and provide additional details, thank you!

**Comment by ChaosCA** [comment]
Please note the first sentence,
```
If you create a new index using the DSL that has settings in it's class Index you will receive errors from elasticsearch as the index has already been created.
```

This index does not already exist, creating an index for the first time with settings results in the error I posted above.

**Comment by HonzaKral** [comment]
I am sorry but I cannot replicate the issue and all the tests that are regularly create index with settings are always green. See for example https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_examples/test_completion.py#L7

Could you provide a sample of code that would replicate this on an empty cluster? How are you running your code?

**Comment by ChaosCA** [comment]
@HonzaKral Hm, interesting.

I'm unsure why the issue would only appear on my end in that case. The code I ran is what I posted above, and it's rather basic. I adjusted the setting manually in production on the created index and caught the exception on startup (since my application creates the index if it doesn't exist). 
Thanks anyways, glad there's a test case in place.

**Comment by HonzaKral** [comment]
What do you mean application? Is it like a wsgi-based web application? Could it be that your application has multiple workers that start at the same time so you have a race condition there where several of them try to create the index at the same time? That would certainly explain this behavior..

**Comment by ChaosCA** [comment]
That's actually very possibly the issue. It is a WSGI based web app. I don't suppose you have any recommendations on that front?

**Comment by HonzaKral** [comment]
I do, don't create the index in your application code but instead treat it more as a database migration, run it once as part of the deploy process from a single point before starting your application, that should eliminate this. Another option is to ignore the `400` exception - just catch it and ignore - but that might mask some legitimate errors so wouldn't be my first recommendation for sure.

**Comment by ChaosCA** [comment]
Awesome, will do through a custom Django command.

Thank you.
