### ISSUE TITLE
Search documents with array containing given value

### ISSUE THREAD

**Issue by passwordleak** [elastic/elasticsearch-dsl-py#1188]
I have a document that looks like this 
```
{
types: ["a","b","c"] 
}
```
I need to search for all documents that include a type "b". I tried 
`search().filter('term', types='b')`

but all that does it search for where the first element is "b". How can I search for documents where any member of the array is "b"?

**Comment by HonzaKral** [comment]
The search that you have is exactly what you need and works for any item in the list:

```python
from elasticsearch_dsl import connections, Document, Keyword

connections.create_connection()

class D(Document):
    tags = Keyword(multi=True)
    class Index:
        name = 'i'

D.init()
D(tags=['a', 'b', 'c']).save(refresh=True)

# now any of these searches will return our document
D.search().filter('term', tags='a').count()
D.search().filter('term', tags='b').count()
D.search().filter('term', tags='c').count()
```

Hope this helps!

**Comment by passwordleak** [comment]
Your code works when I remove D.init(). Found out my problem is because I included a dot in my array. Now my problem is when I set it as not_analyzed, it doesn't do anything. Apparently, that's because I need to use .init(). 

```
Traceback (most recent call last):
  File "/test.py", line 10, in <module>
    D.init()
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 136, in init
    i.save(using=using)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 307, in save
    self.put_mapping(using=using, body=mappings)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 398, in put_mapping
    return self._get_connection(using).indices.put_mapping(index=self._name, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 339, in put_mapping
    "PUT", _make_path(index, "_mapping", doc_type), params=params, body=body
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 239, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: mapping type is missing;')
```
