### ISSUE TITLE
TypeError on document save()

### ISSUE THREAD

**Issue by akajb84** [elastic/elasticsearch-dsl-py#1321]
I'm trying to set up a little test script to create an index, and then save a single document to it. While a previous script I had worked, I'm now running into an error every time I try to save (and the old script seems to hit this now, too). The index is created, so are the proper document mappings. And then, when it gets to the save line, I get: `TypeError: index() missing 1 required positional argument: 'doc_type'`

Full error is:
```
Traceback (most recent call last):
  File "es_activity2.py", line 52, in <module>
    new_act.save(using=client)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/document.py", line 456, in save
    **doc_meta
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: index() missing 1 required positional argument: 'doc_type'
```

I've tried searching, but I'm not having any luck figuring out what has caused this. 

My tiny test script is below.

```
from elasticsearch import Elasticsearch
from elasticsearch_dsl import (
    Index,
    Document,
    Date,
    Integer,
    Keyword,
    analysis,
    Boolean,
)

client = Elasticsearch(hosts=[{"host": "localhost", "port": 29200}])

class Activity(Document):
    account_id = Keyword()
    client_id = Keyword()
    created_ts = Date()
    updated_ts = Date()
    timestamp = Date()
    snapshots = Boolean()

    class Index:
        name = "activity2_test"
        settings = {"number_of_shards": 1}


Activity.init(using=client)

# print out the mappings
activity = Index("activity2_test")
mappings = activity.get_mapping(using=client)


print("\n***** MAPPINGS *****\n")
print(mappings)

# example entry
act = {
    "account_id": "test_account_id",
    "client_id": "test_client_id",
    "created_ts": 1540491926,
    "updated_ts": 1540491926,
    "snapshots": False,
    "history": {
        "snapshot": 1,
        "created_ts": 1540491926,
        "content": "This is the first entry",
    },
}

new_act = Activity(meta={"id": act["account_id"] + "_" + act["client_id"]})
new_act.account_id = act["account_id"]
new_act.client_id = act["client_id"]
new_act.created_ts = act["created_ts"]
new_act.updated_ts = act["updated_ts"]
new_act.snapshots = act["snapshots"]
new_act.save(using=client)
```

**Comment by yash04singh** [comment]
Give doc_type in class index
class Index:
        name = "activity2_test"
        doc_type = "activity"
        settings = {"number_of_shards": 1}

**Comment by sethmlarson** [comment]
I think this should be fixed in recent versions of elasticsearch-py now that `doc_type` defaults to `_doc`.
