### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticsearch.helpers'  in Django

### ISSUE THREAD

**Issue by ynareshkalyan21** [elastic/elasticsearch-dsl-py#1490]
Getting error on starting Django sever, How can I  resolve it ? 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django_elasticsearch_dsl/__init__.py", line 3, in <module>
    from .documents import Document  # noqa
  File "/Users/nareshyarramsetti/envmines/elasticsearch/lib/python3.7/site-packages/django_elasticsearch_dsl/documents.py", line 8, in <module>
    from elasticsearch.helpers import bulk, parallel_bulk
ModuleNotFoundError: No module named 'elasticsearch.helpers'

**Comment by sethmlarson** [comment]
This project is `elasticsearch-dsl`, not `django-elasticsearch-dsl`. [Perhaps you meant this project](https://github.com/django-es/django-elasticsearch-dsl)?
