### ISSUE TITLE
The `Elasticsearch` object obtained via the `elasticsearch_dsl.Connections` abstaction has unexpected behaviour, when used as a contextmanager

### ISSUE THREAD

**Issue by lonetwin** [elastic/elasticsearch-dsl-py#1544]
The `ElasticSearch` object, obtained, for example from the module level globals in `elasticsearch_dsl.connections` have surprising and unexpected behavior for anyone used to the object from the `elasticsearch-py` .

```
elasticsearch_dsl == from master ( 7874040b4f1346552a77b6f2a16321f2e1a6c722 )
elasticsearch == 7.13.5
elasticsearch server == elasticsearch-oss-7.10.2 docker instance

```
```python
>>> from elasticsearch_dsl.connections import get_connection, create_connection
>>> es_conn = create_connection()
>>> es_conn.cat.health()
'1635860762 13:46:02 docker-cluster yellow 1 1 3 3 0 0 3 0 - 50.0%\n'
>>> with get_connection() as new_conn:
...     print (new_conn.cat.health())
...
1635860791 13:46:31 docker-cluster yellow 1 1 3 3 0 0 3 0 - 50.0%

>>> es_conn.cat.health()
Traceback (most recent call last):
  File "/home/sfernandez/src/elasticsearch-dsl-py/.env_python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 257, in _get_conn
    conn = self.pool.get(block=self.block, timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sfernandez/src/elasticsearch-py/elasticsearch/connection/http_urllib3.py", line 251, in perform_request
    response = self.pool.urlopen(
  ...
  File "/home/sfernandez/src/elasticsearch-dsl-py/.env_python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 260, in _get_conn
    raise ClosedPoolError(self, "Pool is closed.")
urllib3.exceptions.ClosedPoolError: HTTPConnectionPool(host='localhost', port=9200): Pool is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sfernandez/src/elasticsearch-py/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  ...
  File "/home/sfernandez/src/elasticsearch-py/elasticsearch/connection/http_urllib3.py", line 266, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Pool is closed.) caused by: ClosedPoolError(HTTPConnectionPool(host='localhost', port=9200): Pool is closed.)
>>>
>>>
>>> get_connection().cat.health()
Traceback (most recent call last):
  File "/home/sfernandez/src/elasticsearch-dsl-py/.env_python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 257, in _get_conn
  ...<SAME AS ABOVE>...
  File "/home/sfernandez/src/elasticsearch-py/elasticsearch/connection/http_urllib3.py", line 266, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Pool is closed.) caused by: ClosedPoolError(HTTPConnectionPool(host='localhost', port=9200): Pool is closed.)
>>>

```

From what I can tell, this is because the `__exit__` method of `Elasticsearch` object closes connections.

Not quite sure what the best 'fix' for this might be. Perhaps to not close the connection on `__exit__` if the object was instantiated outside of a contextmanager ? (ie: fix this in elasticsearch-py ?)

**Comment by miguelgrinberg** [comment]
Upon closer inspection, I'm going to close this issue. The documentation does not encourage the direct use of ES client instances in the way you show here, instead the recommendation is that you create your own client instance and pass it to `Search()` and other objects with the `using` argument.
