### ISSUE TITLE
Question: Custom analyzer and filter Elasticsearch DSL py timing out on index creation

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [elastic/elasticsearch-dsl-py#1571]
Elasticsearch is erroring when I'm trying to make an analyzer and a filter, and then creating an index. The following is using Elasticsearch dsl py on latest major version 7. What this code is trying to do is create a Synonym analyzer and filter using Wordnet as demonstrated here in the docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html

```python
from elasticsearch_dsl import (
    Document, Text, Date, Integer, analyzer, connections, tokenizer, token_filter,
)


connections.create_connection(hosts=["localhost"])

# https://github.com/elastic/elasticsearch-dsl-py/issues/891
# https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html
synonym_filter = token_filter("synonym", type="synonym", synonyms_path="extra/wn_s.pl")
synonym_analyzer = analyzer(
    "synonym",
    tokenizer=tokenizer("whitespace"),
    filter=[synonym_filter],
)


class Comment(Document):
    author = Text()
    body = Text(analyzer=synonym_analyzer)
    created_utc = Date()
    id = Text()
    link_id = Text()
    parent_id = Text()
    subreddit = Text()
    subreddit_id = Text()
    score = Integer()

    keys = (
        "author",
        "body",
        "created_utc",
        "id",
        "link_id",
        "parent_id",
        "subreddit",
        "subreddit_id",
        "score",
    )

    class Index:
        name = "reddit_comments"
        settings = {
            "number_of_shards": 2,
        }

```

I run this with `Comment.init()`

But I'm getting this error:

```
/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py --mode=client --port=53282
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/andrewcwang/Work/Code/projects/python/argue-bot'])
Python 3.9.10 (main, Jan 15 2022, 11:48:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.1.0
Python 3.9.10 (main, Jan 15 2022, 11:48:04) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
from app.models.comment import Comment
Comment.init()
/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 255, in perform_request
    response = self.pool.urlopen(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3340, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a3eb79b67585>", line 1, in <cell line: 1>
    Comment.init()
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/document.py", line 156, in init
    i.save(using=using)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/index.py", line 299, in save
    return self.create(using=using)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/index.py", line 279, in create
    return self._get_connection(using).indices.create(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/client/indices.py", line 145, in create
    return self.transport.perform_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 279, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
Comment.init()
/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 255, in perform_request
    response = self.pool.urlopen(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3340, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-a3eb79b67585>", line 1, in <cell line: 1>
    Comment.init()
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/document.py", line 156, in init
    i.save(using=using)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/index.py", line 299, in save
    return self.create(using=using)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch_dsl/index.py", line 279, in create
    return self._get_connection(using).indices.create(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/client/indices.py", line 145, in create
    return self.transport.perform_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/andrewcwang/Work/Code/projects/python/argue-bot/venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 279, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
```

I've also ensured that the instance is communicable:

```
>>> connections.get_connection().ping()
True
```

So what can I do to fix this to create the index? I tried following this but again not working: https://stackoverflow.com/questions/50017403/create-custom-analyzer-filter-for-a-index-in-py-elasticsearch-dsl which coincides with #891 . Thanks for any help!

**Comment by Andrew-Chen-Wang** [comment]
Nevermind, it's just... timing out since I seem to be able to create new docs?

**Comment by Andrew-Chen-Wang** [comment]
nvm I think I just needed to increase the timeout to 60
