### ISSUE TITLE
Read timeout on UpdateByQuery.script

### ISSUE THREAD

**Issue by johann-petrak** [elastic/elasticsearch-dsl-py#1582]
I am running a script (which requires quite some time to run) via UpdateByQuery like so
```
byq = UpdateByQuery(index=args.i).using(esclient).script(source=SCRIPT)
response = byq.execute()
```
This throws an exception: 
```
Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/connection/http_urllib3.py", line 255, in perform_request
    response = self.pool.urlopen(
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='THEHOST', port=9999): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../python/project_fcdo/es-add-orig-time.py", line 26, in <module>
    response = byq.execute()
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7_dsl/update_by_query.py", line 158, in execute
    es.update_by_query(index=self._index, body=self.to_dict(), **self._params),
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/client/__init__.py", line 2218, in update_by_query
    return self.transport.perform_request(
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/transport.py", line 466, in perform_request
    raise e
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/johann/software/anaconda3/envs/fcdo/lib/python3.8/site-packages/elasticsearch7/connection/http_urllib3.py", line 279, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch7.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='THEHOST', port=9999): Read timed out. (read timeout=10))
```

The documentation at https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#update-by-query does not mention any parameter or method to set the timeout. 
Is there a way to set the timeout specifically for this operation without setting it for all operations?
If not, what would be the correct way to set the timeout when creating the esclient? The documentation of the elasticsearch package unfortunately never mentions this anywhere either.

**Comment by johann-petrak** [comment]
It is also not clear to me how to specify `wait_for_completion=false` when using this API and how to then check for the status of the task separately?

**Comment by wxd** [comment]
I've used something along the following lines:

```python
es_client = elasticsearch.Elasticsearch(...)
index_name = ...

ubq = elasticsearch_dsl.UpdateByQuery(
    using=es_client,
    index=index_name,
).params(wait_for_completion=False)

response = ubq.execute()  # Returns an object similar to {"task": "1234"}
ubq_task_id = response.task

ubq_task_status = es_client.tasks.get(ubq_task_id)
if ubq_task_status["completed"]:
    response_dict = ubq_task_status["response"]

    # If a response of the same type as `ubq.execute()`
    # with `wait_for_completion=True` is required
    response = elasticsearch_dsl.response.UpdateByQueryResponse(
        elasticsearch_dsl.search.Search(using=es_client),
        response,
    )
```

FWIW this works with rather old versions:
```
elasticsearch==7.17.6
elasticsearch-dsl==7.3.0
```
