### ISSUE TITLE
AttributeError: type object 'CategoryDocument' has no attribute 'to_field'

### ISSUE THREAD

**Issue by bazhil** [elastic/elasticsearch-dsl-py#1618]
Try use elasticsearch in my educate DRF project. Use this article (https://testdriven.io/blog/django-drf-elasticsearch/) as tuitorial. After all settings have error in console: 

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/home/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/home/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/home/anaconda3/lib/python3.9/site-packages/django_elasticsearch_dsl/apps.py", line 14, in ready
    self.module.autodiscover()
  File "/home/home/anaconda3/lib/python3.9/site-packages/django_elasticsearch_dsl/__init__.py", line 11, in autodiscover
    autodiscover_modules('documents')
  File "/home/home/anaconda3/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/home/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/home/PycharmProjects/search_auto/endpoint/documents.py", line 15, in <module>
    class CategoryDocument(Document):
  File "/home/home/anaconda3/lib/python3.9/site-packages/django_elasticsearch_dsl/registries.py", line 65, in register_document
    field_instance = document.to_field(field_name, django_field)
AttributeError: type object 'CategoryDocument' has no attribute 'to_field'_

Please help me resolve this problem.
Pastebin with file "documents.py": https://pastebin.com/7AhNZYwb
Repositry with all code: https://github.com/bazhil/search_auto

**Comment by bazhil** [comment]
Problem was in wrong import Document.
Right way: "from django_elasticsearch_dsl import Document"
