### ISSUE TITLE
Pickling documents containing Nested properties fails

### ISSUE THREAD

**Issue by arsham** [elastic/elasticsearch-dsl-py#164]
Hi,

In following snippet: 

```python
from elasticsearch_dsl import DocType, Nested, Long, String


class ExampleDoc(DocType):
    content = Nested(
        properties={
            'id': Long(),
            'title': String(
                index='not_analyzed',
                fields={'raw': String(index='not_analyzed', ignore_above=100)},
            )
        }
    )

s = ExampleDoc()
s.content = {'id': 1, 'title': 'example title'}
import pickle
pickle.dumps(s)
```

I get this error: 

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib64/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <class 'elasticsearch_dsl.field.Meta'>: it's not found as elasticsearch_dsl.field.Meta

```

Thank you,
Arsham

**Comment by HonzaKral** [comment]
Thanks for the report and sorry for the delay.

**Comment by arsham** [comment]
Cheers for the fix mate :)
