### ISSUE TITLE
Caused elasticsearch.exceptions.SSLError after elasticsearch-dsl-py installed.

### ISSUE THREAD

**Issue by evakichi** [elastic/elasticsearch-dsl-py#1667]
I can run the Elasticsearch with python using elasticsearch-py. At this time, I can connect Elasticsearch server.
Then, I have installed elasticsearch-dsl-py. After that I could not connect this server.
I read about workaround in detail that we should add `verify_certs=False`.
I added it to my script. 
But I could not connect this server with another problem.

How can I solve it ?

First, I described as follows,
```
from elasticsearch import Elasticsearch

es =  Elasticsearch(
    "https://my_ip_addr:9200",
    ssl_assert_fingerprint="fingerprint",
    basic_auth=("elastic", "mypasswd")
)

es.info()
```
I encountered following error
```
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./minset.py", line 10, in <module>
    es.info()
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 295, in info
    return self.transport.perform_request(
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 417, in perform_request
    self._do_verify_elasticsearch(headers=headers, timeout=timeout)
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 606, in _do_verify_elasticsearch
    raise error
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 569, in _do_verify_elasticsearch
    _, info_headers, info_response = conn.perform_request(
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    raise SSLError("N/A", str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError(("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])",)) caused by: SSLError(("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])",))
```
Second, I added `verify_certs=False` along with many suggestions, then I encountered following error,
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://my_ip_addr:9200 using SSL with verify_certs=False is insecure.
  warnings.warn(
./minset.py:11: ElasticsearchWarning: The client is unable to verify that the server is Elasticsearch due security privileges on the server side
  es.info()
Traceback (most recent call last):
  File "./minset.py", line 11, in <module>
    es.info()
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 295, in info
    return self.transport.perform_request(
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mishihara/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 328, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/]')
``` 

My environments is described as follows,
```
$ pip list|grep elasticsearch
elasticsearch                 7.17.9
elasticsearch-dsl             7.4.1
$ pip3 install elasticsearch-dsl
Requirement already satisfied: elasticsearch-dsl in /home/mishihara/.local/lib/python3.8/site-packages (7.4.1)
Requirement already satisfied: elasticsearch<8.0.0,>=7.0.0 in /home/mishihara/.local/lib/python3.8/site-packages (from elasticsearch-dsl) (7.17.9)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from elasticsearch-dsl) (1.14.0)
Requirement already satisfied: python-dateutil in /home/mishihara/.local/lib/python3.8/site-packages (from elasticsearch-dsl) (2.8.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /home/mishihara/.local/lib/python3.8/site-packages (from elasticsearch<8.0.0,>=7.0.0->elasticsearch-dsl) (1.26.16)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from elasticsearch<8.0.0,>=7.0.0->elasticsearch-dsl) (2019.11.28)
$ pip3 install elasticsearch
Requirement already satisfied: elasticsearch in /home/mishihara/.local/lib/python3.8/site-packages (7.17.9)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from elasticsearch) (2019.11.28)
Requirement already satisfied: urllib3<2,>=1.21.1 in /home/mishihara/.local/lib/python3.8/site-packages (from elasticsearch) (1.26.16)
```
Thanks!!

**Comment by evakichi** [comment]
Sorry I can resolve.
```
$ pip3 uninstall elasticsearch-dsl
$ pip3 uninstall elasticsearch
$ pip3 install elasticsearch
```
It's wrong question...
