### ISSUE TITLE
Iterating over search results occasionally raises KeyError('hits')

### ISSUE THREAD

**Issue by knoebber** [elastic/elasticsearch-dsl-py#1919]
Has anyone seen this before? Any idea on how to fix it?

**Comment by miguelgrinberg** [comment]
I need to see the code that you are using and the exception you are getting, including the stack trace please.

**Comment by knoebber** [comment]
I can't share all the code I'm using. The stack trace from the es_dsl
library is:

```
File <our private code base>, line 1695, in <listcomp>#012 return
[ProductViewModel(product_document) for product_document in self]
 File "elasticsearch_dsl/_sync/search.py", line 46, in __next__#012
self.iterator = iter(self.search.execute())#012
 File "elasticsearch_dsl/response/__init__.py", line 60, in __iter__#012
return iter(self.hits)#012
 File "elasticsearch_dsl/response/__init__.py", line 95, in hits#012 h =
cast(AttrDict[Any], self._d_["hits"])#012KeyError: 'hits'
```

Typically this call succeeds. It seems like elasticsearch is returning an
empty response for hits? I'm mostly just wondering if this is a problem
anyone else has encountered before.

**Comment by pquentin** [comment]
For some reason, the stack trace does not format correctly. Trying with a new comment:


```python
File <our private code base>, line 1695, in <listcomp>#012
  return [ProductViewModel(product_document) for product_document in self]
File "elasticsearch_dsl/_sync/search.py", line 46, in __next__#012
  self.iterator = iter(self.search.execute())#012
File "elasticsearch_dsl/response/__init__.py", line 60, in __iter__#012
  return iter(self.hits)#012
File "elasticsearch_dsl/response/__init__.py", line 95, in hits#012
  h = cast(AttrDict[Any], self._d_["hits"])#012
KeyError: 'hits'
```

**Comment by knoebber** [comment]
Thanks @pquentin .

Update:

1. The error only happens in celery tasks
2. The exception is raised because responses appear to be mixed up, e.g. a search request receives a response body from a get request, so the 'hits' key isn't present

I think this is the root cause: https://github.com/urllib3/urllib3/issues/850. Has anyone encountered this?  Does the elasticsearch client library expose a way to reset the connection pools? Should I just create a new client before every celery task starts?

I'm going to close this now since it's not related to this library, but I would appreciate any advice! Thanks :)

**Comment by pquentin** [comment]
I happen to also maintain urllib3, and I'm a bit confused. Is Celery using `fork` for each new task? Is it possible to reproduce this bug?

**Comment by knoebber** [comment]
It's not easily reproducible. It only happened very rarely while processing large queues. I fixed the bug by recreating the elasticsearch client before each task runs.

There are other reports of celery causing this issue, for example: https://github.com/urllib3/urllib3/issues/850#issuecomment-333643433

Celery does use fork. I don't know all the specifics though.

**Comment by selimt** [comment]
I am also running into this issue with Celery 5.5.3 and elasticsearch 8.19.0:

```
2025-08-19T19:54:17.796566887Z [2025-08-19 19:54:17,796: ERROR/ForkPoolWorker-5] Task sync_connection[b72aa159-6be8-4083-b987-4d42f748a413] raised unexpected: KeyError('hits')
2025-08-19T19:54:17.796613702Z Traceback (most recent call last):
2025-08-19T19:54:17.796619810Z   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
2025-08-19T19:54:17.796624592Z     R = retval = fun(*args, **kwargs)
2025-08-19T19:54:17.796628642Z   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
2025-08-19T19:54:17.796632876Z     return self.run(*args, **kwargs)
2025-08-19T19:54:17.796637259Z   File "/usr/local/lib/python3.10/site-packages/catalog/tasks/sync/tasks.py", line 212, in sync_connection
2025-08-19T19:54:17.796641721Z     if len(hits) > 0:
2025-08-19T19:54:17.796646159Z   File "/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/response/__init__.py", line 137, in __len__
2025-08-19T19:54:17.796650559Z     return len(self.hits)
2025-08-19T19:54:17.796654470Z   File "/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/response/__init__.py", line 155, in hits
2025-08-19T19:54:17.796659153Z     h = cast(AttrDict[Any], self._d_["hits"])
2025-08-19T19:54:17.796663201Z KeyError: 'hits'
```
