### ISSUE TITLE
[bug] Type hints are not working correctly when using python 3.12

### ISSUE THREAD

**Issue by pySilver** [elastic/elasticsearch-dsl-py#1928]
Documents declaration works when `Optional` is used:

```python
class MyDocument(Document):
    label: Optional[str]

doc = MyDocument(label="test")
print(doc.full_clean()) # Prints no error ie. None
```

however more recent syntax for Optional is different:

```python
class MyDocument(Document):
    label: str | None

doc = MyDocument(label="test")
print(doc.full_clean()) # prints errors
```
Errors:

```
Traceback (most recent call last):
  File "/Users/Silver/Projects/GitHub/mybaze/temp.py", line 77, in <module>
    main()
  File "/Users/Silver/Projects/GitHub/mybaze/temp.py", line 63, in main
    class MyDocument(Document):
  File "/Users/Silver/Projects/GitHub/mybaze/.venv/lib/python3.12/site-packages/elasticsearch_dsl/_sync/document.py", line 56, in __new__
    new_cls = super().__new__(cls, name, bases, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Silver/Projects/GitHub/mybaze/.venv/lib/python3.12/site-packages/elasticsearch_dsl/document_base.py", line 109, in __new__
    attrs["_doc_type"] = DocumentOptions(name, bases, attrs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Silver/Projects/GitHub/mybaze/.venv/lib/python3.12/site-packages/elasticsearch_dsl/document_base.py", line 236, in __init__
    raise TypeError(f"Cannot map field {name}")
TypeError: Cannot map field label
```

**Comment by miguelgrinberg** [comment]
We support `Optional`, as documented. The pipe syntax may or may not work, I did not attempt to support it at this time.

Also note that typing in this libray is a recent effort and we are making it better with every release, but it cannot be considered a completed effort at this time.
