### ISSUE TITLE
How can I pass an uncertain list of sorting-keys into .sort() method?

### ISSUE THREAD

**Issue by Windfarer** [elastic/elasticsearch-dsl-py#205]
I tried to pass some sorting-keys in a list to .sort() method.
example:
```
sorting = ['-date','title','name']
```
and this sorting-key list is generated dynamically, so I can't pass every key into the sort method as usual position args.
  
When I pass this list into .sort() method, it raised an exception.
So how can I do that?
Thanks a lot.

**Comment by njoannin** [comment]
@Windfarer It would be much easier to help you if you could post the a working example as well as the exception that it raises... Could you update your question with that?

**Comment by Windfarer** [comment]
ok, this is a more detailed example

```python
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

client = Elasticsearch()
s = Search(using=client, index='blog').query("match", blog_title="1").sort("title","blog_date") # this works well
resp = s.execute()
print(resp)

# when i pass a list into sort()
sorting_list = ["blog_title","blog_date"] 
s = Search(using=client, index='blog').query("match", blog_title="1").sort(sorting_list) # this will raise an exception
resp = s.execute()

```

The exception is as follows

```
GET /blog/_search [status:400 request:0.017s]
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    resp = s.execute()
  File "/usr/local/lib/python3.4/site-packages/elasticsearch_dsl/search.py", line 468, in execute
    **self._params
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 506, in search
    params=params, body=body)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[3l4VTElGTd6TW_DPcX7VnQ][blog][0]: SearchParseException[[blog][0]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": [["blog_title", "blog_date"]]}]]]; nested: ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]; }{[3l4VTElGTd6TW_DPcX7VnQ][blog][1]: SearchParseException[[blog][1]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": [["blog_title", "blog_date"]]}]]]; nested: ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]; }{[3l4VTElGTd6TW_DPcX7VnQ][blog][2]: SearchParseException[[blog][2]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": [["blog_title", "blog_date"]]}]]]; nested: ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]; }{[3l4VTElGTd6TW_DPcX7VnQ][blog][3]: SearchParseException[[blog][3]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": [["blog_title", "blog_date"]]}]]]; nested: ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]; }{[3l4VTElGTd6TW_DPcX7VnQ][blog][4]: SearchParseException[[blog][4]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": [["blog_title", "blog_date"]]}]]]; nested: ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]; }]')
```

**Comment by Windfarer** [comment]
I think that the sort method may not deal with the list correctly.

**Comment by njoannin** [comment]
@Windfarer  There you have it, at the end of the error message.

```
ElasticsearchIllegalArgumentException[malformed sort format, within the sort array, an object, or an actual string are allowed]
```

Indeed, it does not seem to accept a list as argument.

Instead you can do this:

```
s = Search(...).query(...).sort(", ".join(sorting_list))
```

@HonzaKral:  Could you tell us what ```object``` we could use instead of a string, if there is one?

**Comment by Windfarer** [comment]
I edited my code as
```python
...
s = Search(using=client, index='blog').query("match", blog_title="1").sort(', '.join(sorting_list))
```
but it seems this doesn't work.  
Exception message as:

```
GET /blog/_search [status:400 request:0.007s]
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    resp = s.execute()
  File "/usr/local/lib/python3.4/site-packages/elasticsearch_dsl/search.py", line 468, in execute
    **self._params
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 506, in search
    params=params, body=body)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[SuhEQWFwR0Wddp9Qqe9K_g][blog][0]: SearchParseException[[blog][0]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][0]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][1]: SearchParseException[[blog][1]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][1]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][2]: SearchParseException[[blog][2]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][2]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][3]: SearchParseException[[blog][3]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][3]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][4]: SearchParseException[[blog][4]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][4]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }]')
```

**Comment by HonzaKral** [comment]
It needs to be passed as individual args, potentially starting with '-' if you want descending order: `s = s.sort('field2', '-field2')`

Alternatively you can pass in a dict instead of string if you need to specify more options.

Sorry for brevity, traveling and only have cellphone

**Comment by njoannin** [comment]
@Windfarer Again, if you look at raised exception, you will find a hint as to the problem:

The last line of the error is this:

```
elasticsearch.exceptions.RequestError: TransportError(400, 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[SuhEQWFwR0Wddp9Qqe9K_g][blog][0]: SearchParseException[[blog][0]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][0]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][1]: SearchParseException[[blog][1]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][1]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][2]: SearchParseException[[blog][2]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][2]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][3]: SearchParseException[[blog][3]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][3]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }{[SuhEQWFwR0Wddp9Qqe9K_g][blog][4]: SearchParseException[[blog][4]: query[blog_title:1],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"match": {"blog_title": "1"}}, "sort": ["blog_title, blog_date"]}]]]; nested: SearchParseException[[blog][4]: query[blog_title:1],from[-1],size[-1]: Parse Failure [No mapping found for [blog_title, blog_date] in order to sort on]]; }]')
```

From that, at the very end:

```
[No mapping found for [blog_title, blog_date] in order to sort on]
```

There might be a problem with the mapping of your index.

**Comment by Windfarer** [comment]
But this shouldn't be an index mapping problem,  like above example, if I pass the args directly to sort method, it will return correct response.   
So how could I pass a serial of args into sort method, if these args are not hard coded in the script?

**Comment by HonzaKral** [comment]
`s = s.sort(*sorting)`

**Comment by njoannin** [comment]
@Windfarer 

In your working example, you used ```.sort("title","blog_date")```; whereas in your failing example you used ```.sort(", ".join(sorting_list)```, where ```sorting_list = ["blog_title","blog_date"]```.

So, might there be a problem with your mapping, in that your mapping actually has a field named ```title``` and not one named ```blog_title```?

I know that I sometimes make those kind of small typos that drive me crazy ;)

@HonzaKral 

Is your suggestion for using with a list? As in:

```
sorting = ["field1", "field2"]
s = s.sort(*sorting)
```

**Comment by HonzaKral** [comment]
Yes, if you know what you sort on, just pass it directly as: `s = s.sort('one_field', 'other_field')` otherwise store it in a list and use the `*` operator so that python will unroll the list as parameters.

In order to access the documentation just look at the docstring of the `sort` method using standard python `help` command:

    from elasticsearch_dsl import Search
    s = Search()
    help(s.sort)

where you can also find examples.

Hope this helps.

**Comment by njoannin** [comment]
@HonzaKral Very cool, thanks! (I very rarely use the ```*``` operator but certainly should use it more.)

**Comment by HonzaKral** [comment]
Closing this ticket, please reopen if problems persist.

I will work on including the method docstrings in the official docs.
