### ISSUE TITLE
TypeError occurs if document contains field named 'self' or 'meta'

### ISSUE THREAD

**Issue by wataru-chocola** [elastic/elasticsearch-dsl-py#240]
A document which has a field named 'self' or 'meta' makes DocType.get() raise TypeError.

----

On latest master's commit ( 50337e1d5f7260723d1883f5423a7e812d0b9ae6 )

Test code:

```python
import elasticsearch_dsl

class Test(elasticsearch_dsl.DocType):
    class Meta:
        index = 'test'

if __name__ == '__main__':
    elasticsearch_dsl.connections.connections.configure(default={'hosts': 'localhost:9200'})
    es = elasticsearch_dsl.connections.connections.get_connection()
    es.index(index='test', doc_type='test', body={'self':1}, id=1)

    testdoc = Test.get(id = 1)
    print testdoc.to_dict()
```

Result:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    testdoc = Test.get(id = 1)
  File "/tmp/test/venv_test/src/elasticsearch-dsl/elasticsearch_dsl/document.py", line 143, in get
    return cls.from_es(doc)
  File "/tmp/test/venv_test/src/elasticsearch-dsl/elasticsearch_dsl/document.py", line 160, in from_es
    return cls(meta=meta, **doc)
TypeError: __init__() got multiple values for keyword argument 'self'
```

**Comment by wataru-chocola** [comment]
Sorry, I missed #229
