### ISSUE TITLE
Custom analyzer on _all field causes SerializationError on init

### ISSUE THREAD

**Issue by gmacon** [elastic/elasticsearch-dsl-py#310]
This:

```python
from elasticsearch_dsl import DocType, analyzer, MetaField, String
from elasticsearch_dsl.connections import connections

an = analyzer('my_analyzer')

class Foo(DocType):
    class Meta:
        index = 'foo'

        all = MetaField(search_analyzer=an, index_analyzer=an)

    foo = String()

connections.create_connection(hosts=['localhost'])
Foo.init()
```
raises `SerializationError` when trying to create the mapping.  I think this bug is in `Mapping.to_dict`, but I'm not sure of the correct approach here for fixing the bug.

Here's the stack trace:

```
Traceback (most recent call last):
  File "minimal.py", line 16, in <module>
    Foo.init()
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 126, in init
    cls._doc_type.init(index, using)
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 89, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch_dsl/mapping.py", line 68, in save
    es.indices.create(index=index, body={'mappings': self.to_dict(), 'settings': {'analysis': self._collect_analysis()}})
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch/transport.py", line 273, in perform_request
    body = self.serializer.dumps(body)
  File "/usr/local/var/pyenv/versions/foo/lib/python2.7/site-packages/elasticsearch/serializer.py", line 47, in dumps
    raise SerializationError(data, e)
elasticsearch.exceptions.SerializationError: ({'mappings': {'foo': {'_all': {'search_analyzer': CustomAnalyzer(), 'index_analyzer': CustomAnalyzer()}, 'properties': {'foo': {'type': 'string'}}}}, 'settings': {'analysis': {}}}, TypeError("Unable to serialize CustomAnalyzer() (type: <class 'elasticsearch_dsl.analysis.CustomAnalyzer'>)",))
```

**Comment by HonzaKral** [comment]
Thanks for reporting this, it is definitely a bug where we don't serialize `mapping._meta` properly.

I added a small change in 508448e to make the serializer more lenient, it also works as a workaround for this, but real fix is coming.
