### ISSUE TITLE
Strange import error under Django's management shell

### ISSUE THREAD

**Issue by robhudson** [elastic/elasticsearch-dsl-py#35]
While testing some code locally I ran into this. I boiled it down to as minimal a query as I could that causes the issue. I'm guessing something within elasticsearch_dsl is causing this?

```
$ ./manage.py shell --plain
Using settings_local.py
Raven is not configured (logging is disabled). Please see the documentation for more information.
Python 2.7.8 (default, Oct 27 2014, 15:34:41)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from elasticsearch_dsl import filter as es_filter
>>> from elasticsearch_dsl import Search
>>> Search().filter(es_filter.Bool(should=[es_filter.Bool(must=[es_filter.Term(id=6)])])).execute()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/rob/.virtualenvs/zamboni/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 79, in handle_noargs
    raise ImportError
ImportError
```

**Comment by whiler** [comment]
fix it, add these codes into `manage.py` .

```
import sys

sys.ps1 = '>>> '
sys.ps2 = '... '
```

**Comment by whiler** [comment]
or remove monkey.patch_all
