### ISSUE TITLE
Question about basic code

### ISSUE THREAD

**Issue by Alexis-benoist** [elastic/elasticsearch-dsl-py#361]
Hey Guys,

I'm trying the following code using elasticsearch-dsl:
``` python
from os import getenv
from pyelasticsearch import ElasticSearch
from elasticsearch_dsl import Q, Search

ELASTIC_URL = getenv('ELASTIC_URL', 'http://localhost')
ELASTIC_PORT = int(getenv('ELASTIC_PORT', 9200))

es = ElasticSearch(port=ELASTIC_PORT, urls=ELASTIC_URL)

def query_test():
    s = Search(using=es, index="test")
    for r in s:
        print r


if __name__ == '__main__':
    query_test()
```

I get the following stacktrace.
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Users/alexisbenoist/dev/elastic/load_csv.py", line 98, in <module>
    query_test()
  File "/Users/alexisbenoist/dev/elastic/load_csv.py", line 84, in query_test
    for r in s:
  File "/Users/alexisbenoist/.virtualenvs/elastic/lib/python2.7/site-packages/elasticsearch_dsl/search.py", line 231, in __iter__
    return iter(self.execute())
  File "/Users/alexisbenoist/.virtualenvs/elastic/lib/python2.7/site-packages/elasticsearch_dsl/search.py", line 579, in execute
    **self._params
  File "/Users/alexisbenoist/.virtualenvs/elastic/lib/python2.7/site-packages/pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
TypeError: search() takes exactly 2 arguments (1 given)
```

I'm running python 2.7.11 on El Capitan and I have the following list of requirements:
```
$ 
pip freeze
certifi==2016.2.28
elasticsearch==1.9.0
elasticsearch-dsl==2.0.0
pyelasticsearch==1.4
python-dateutil==2.5.0
simplejson==3.8.2
six==1.10.0
unicodecsv==0.14.1
urllib3==1.14
wheel==0.24.0
```

I'm looking at the internals and I don't really understand. 
I thank you in advance for your help :)

Cheers,
Alexis.

**Comment by HonzaKral** [comment]
Hi, `elasticsearch-dsl` works with `elasticsearch-py`, the official elasticsearch client maintained by elastic. You are using `pyelasticsearch` instead, which is not compatible. Properly it should be:
```
from elasticsearch import Elasticsearch
es = Elasticsearch(hosts=ELASTIC_URL, port=ELASTIC_PORT)
```

Hope this helps

**Comment by Alexis-benoist** [comment]
:+1: 
Silly error from me :) It seemed really non sensical.
