### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by tstallings** [elastic/elasticsearch-dsl-py#379]
I'm trying to create a `DocType` where some of the properties can be another `DocType`

```
class EntryDoc(DocType):
    some_string = String()
    some_ip = Ip()
    some_timestamp = Date()

class ResultsDoc(DocType):
    # obviously this doesn't work but I think you see what I am trying to do
    # It's an array with json structured like EntryDoc and I need it indexed as such
    results = EntryDoc()    
```

I know I can just define the `EntryDoc` in the `properties` of a `Nested` field, but that doesn't quite work so well when I have a subclassed doc. For example:

```
class Enrichment(DocType):
    queryValue = String()
    tags = String()
    wasSuccessful = Boolean()
    queryType = String()

    def __init__(self, jdata):

        GenericDoc.__init__(self)
        for k, v in jdata.items():
            if v is None:
                v = {} # can't be a NoneType or field._serialize breaks
            setattr(self, k, v)

class ExtendedEnrichment(Enrichment):

    source = String()
    sourceUrl = String()
    sample = String()
    collectionDate = Date()

    def __init__(self, jdata):
        Enrichment.__init__(self, jdata)


class ExtendedEnrichmentResponse(DocType):

    results = ExtendedEnrichment() # ???

    def __init__(self, jdata):

        GenericDoc.__init__(self)

        self.results = []
        for result in jdata["results"]:
            self.results.append(ExtendedEnrichment(result))
```

Hopefully this is super easy and I just wasn't seeing it. But I've looked up and down the docs, source code, and unit tests and I'm not seeing it.

**Comment by tstallings** [comment]
Ok...I might have figured out a way to do what I need with something similar to this

```
class EntryDoc(field.InnerObjectWrapper):
    some_string = String()
    some_ip = Ip()
    some_timestamp = Date()

class ResultsDoc(DocType):
    results = Nested(
        doc_class=EntryDoc
    )

    def __init__(self, jdata={}):
        DocType.__init__(self)
        for k, v in jdata.items():
            if v is None:
                v = {}
            setattr(self, k, v)

```

The only problem I've noticed while testing this out is that if I call `my_results_doc.to_dict()`, I cannot call it a second time because it does some sort of mutation on the object and I get an `AttributeError`. Stack trace if you're interested

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tommy.stallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 196, in to_dict
    d = super(DocType, self).to_dict()
  File "/Users/tommy.stallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 349, in to_dict
    v = f.serialize(v)
  File "/Users/tommy.stallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 68, in serialize
    data[:] = map(self._serialize, data)
  File "/Users/tommy.stallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 183, in _serialize
    return data.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
```

I guess my only question at this point is if this way I found is the best way to do this?

**Comment by HonzaKral** [comment]
The `doc_class` must be a subclass of `InnerObjectWrapper` not `DocType`.

I will try and add an example to the documentation that demonstrates this.
