### ISSUE TITLE
AttributeError on calling to_dict on DocTypes with nulled Nested fields

### ISSUE THREAD

**Issue by dshore** [elastic/elasticsearch-dsl-py#494]
nest.py:
```
from elasticsearch_dsl import Nested, DocType, String

class TestDoc(DocType):
    fld = Nested(properties={'val': String()})

s = TestDoc(fld=None)
s.to_dict()
```

python nest.py
```
Traceback (most recent call last):
  File "nest.py", line 7, in <module>
    s.to_dict()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 196, in to_dict
    d = super(DocType, self).to_dict()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/utils.py", line 349, in to_dict
    v = f.serialize(v)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/field.py", line 70, in serialize
    return self._serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/field.py", line 183, in _serialize
    return data.to_dict()
AttributeError: 'NoneType' object has no attribute 'to_dict'

```
Here is a potential solution:
```
class Nested(InnerObject, Field):
    name = 'nested'

    def __init__(self, *args, **kwargs):
        # change the default for Nested fields
        kwargs.setdefault('multi', True)
        super(Nested, self).__init__(*args, **kwargs)

    def _serialize(self, data):
        if not data is None:
            return super(Nested, self)._serialize(data)
```

And test:
```
class NestedNullVal(document.DocType):
    f = field.Nested(properties={'val': field.String()})

def test_null_nested_field():
    s = NestedNullVal(f=None)
    assert s.to_dict() == {}
```

**Comment by HonzaKral** [comment]
Thank you for the report!
