### ISSUE TITLE
folowed the guideline and struckup with this error

### ISSUE THREAD

**Issue by dinuduke** [elastic/elasticsearch-dsl-py#525]
`{u'status': 503, u'error': u'SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed]'}
Traceback (most recent call last):
  File "C:/Users/admin/AppData/Local/Temp/scp08411/home/ubuntu/Dinesh/es_query/demo2_Loop.py", line 79, in <module>
    chuck_data(i,s,f)
  File "C:/Users/admin/AppData/Local/Temp/scp08411/home/ubuntu/Dinesh/es_query/demo2_Loop.py", line 25, in chuck_data
    print("%d documents found" % res['hits']['total'])
UnboundLocalError: local variable 'res' referenced before 
`

**Comment by HonzaKral** [comment]
Hi, can you please share the code that lead to this error? Looks like you had a failed search which lead to the python variable not being defined.

Thanks

**Comment by HonzaKral** [comment]
Closing this issue as there isn't enough information to resolve it. Please feel free to reopen with new information. Thank you
