### ISSUE TITLE
Cannot Pickle Aggregations

### ISSUE THREAD

**Issue by tkinz27** [elastic/elasticsearch-dsl-py#533]
While trying to use elasticsearch-dsl objects in multiprocessing I keep getting pickling failures.

Can reproduce with this simple test...

```
import pickle

from elasticsearch_dsl import A


def main():
    hist = A('date_histogram', field='timestamp',
             interval={'gte': '2016-07-28||/h', 'lt': '2016-07-28||+6h'})

    pickle.dumps(hist)
    input('well')


if __name__ == "__main__":
    main()
```

```
❯ python test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    main()
  File "test.py", line 10, in main
    pickle.dumps(hist)
_pickle.PicklingError: Can't pickle <class 'elasticsearch_dsl.utils.DateHistogram'>: attribute lookup DateHistogram on elasticsearch_dsl.utils failed
```

**Comment by HonzaKral** [comment]
Thank you for the report!
