### ISSUE TITLE
Exception if record has field called 'meta'

### ISSUE THREAD

**Issue by funkybob** [elastic/elasticsearch-dsl-py#562]
```
DocTypeMeta object got multiple values for keyword argument 'meta': TypeError
Traceback (most recent call last):
File "/var/task/auth.py", line 44, in __call__
return self.func(event, context)
File "/var/task/views.py", line 90, in get_object_list
'total': results.hits.total,
File "/var/task/elasticsearch_dsl/result.py", line 46, in hits
hits = AttrList(map(self._get_result, h['hits']))
File "/var/task/elasticsearch_dsl/result.py", line 38, in _get_result
return self._callbacks.get(dt, Result)(hit)
File "/var/task/elasticsearch_dsl/document.py", line 223, in from_es
return cls(meta=meta, **doc)
TypeError: DocTypeMeta object got multiple values for keyword argument 'meta'
```

**Comment by HonzaKral** [comment]
Hi @funkybob, sorry for the delay!

Unfortunately a library like this will always have some limitations as it needs room on your doc types for its functionality, this is one of them. I understand that this is painful but there is no way we can get around it. If you wish you can override `__init__` in your code and rename the param.
