### ISSUE TITLE
RangeFacet on Date field raises ValidationException

### ISSUE THREAD

**Issue by bidoule** [elastic/elasticsearch-dsl-py#665]
Using a `RangeFacet` on a `Date` field results in a `ValidationException` in version 5.3.0 and 5.2.0 (works fine in 5.1.0). 

Here is an example:
```
class Article(DocType):
    title = Text()
    publication_date = Date()

    class Meta:
        index = 'blog'

Article.init()

Article(meta={'id': 42}, title='Hello World', publication_date=datetime(2017, 3, 12)).save()
Article(meta={'id': 37}, title='Bonjour Monde', publication_date=datetime(2016, 2, 12)).save()
```

This faceted search works:
```
class BlogSearch(FacetedSearch):
    doc_types = [Article, ]
    fields = ['title',]

    facets = {
        'publication_freq': DateHistogramFacet(field='publication_date', interval='month')
    }


print(BlogSearch('').execute().facets.publication_freq)
```

But this one fail:
```
class BlogSearch(FacetedSearch):
    doc_types = [Article, ]
    fields = ['title',]

    facets = {
        'publication_range': RangeFacet(field="publication_date", ranges=[
            ('new', ('now-12M/M', 'now/M')),
            ('old', (None, 'now-12M/M')),
        ]),
    }

print(BlogSearch('').execute().facets.publication_range)
```
With this traceback:
```
Traceback (most recent call last):
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/field.py", line 225, in _deserialize
    return parser.parse(data)
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_es.py", line 50, in <module>
    for (key, count, selected) in response.facets.book_size:
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/faceted_search.py", line 169, in facets
    self._faceted_search.filter_values.get(name, ())
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/faceted_search.py", line 67, in get_values
    for bucket in data:
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/utils.py", line 49, in <lambda>
    return map(lambda i: _wrap(i, self._obj_wrapper), self._l_)
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/utils.py", line 14, in _wrap
    return AttrDict(val) if obj_wrapper is None else obj_wrapper(val)
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/response/aggs.py", line 21, in _wrap_bucket
    data, field=self._meta.get('field'))
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/response/aggs.py", line 14, in __init__
    data['key'] = field.deserialize(data['key'])
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/field.py", line 75, in deserialize
    return self._deserialize(data)
  File "/home/apardon/.venvs/librinde/lib/python3.5/site-packages/elasticsearch_dsl/field.py", line 227, in _deserialize
    raise ValidationException('Could not parse date from the value (%r)' % data, e)
elasticsearch_dsl.exceptions.ValidationException: ("Could not parse date from the value ('old')", ValueError('Unknown string format',))
```

In my opinion, the error is in `elasticsearch-dsl-py/elasticsearch_dsl/response/aggs.py`:
```
class Bucket(AggResponse):
    def __init__(self, aggs, search, data, field=None):
        if field:
            data['key'] = field.deserialize(data['key'])  # <- HERE
        super(Bucket, self).__init__(aggs, search, data)
```
You can see that we try to deserialize the key 'old' into a datetime. 

What is the purpose of this line ? Usually, we deserialize a value, never a key. 
By deleting this line, the example above works in both cases. Is it used elsewhere ?

**Comment by HonzaKral** [comment]
Thanks for the report!

The line is needed for `terms` and `date_histogram` aggregations to properly deserialize the key (have a `datetime` object instead of the timestamp) but shouldn't be used in other aggs.

**Comment by bidoule** [comment]
Great!

Keep up the good work and thanks for this lib.
