### ISSUE TITLE
There is no connection with alias 'default'

### ISSUE THREAD

**Issue by leoliuxd** [elastic/elasticsearch-dsl-py#726]
Here is the config:

    searchurl = '192.168.0.1'
    client = Elasticsearch(['http://elasticuser:passwd@' + searchurl + ':9200'])
    body = {
      "query": {
        "bool": {
          "must": [
              {
                  "query_string": {
                      "default_field": "title.cn",
                      "analyzer": "ik_smart",
                      "query": "hilton"
                  }
              }
          ],
        }
      }
    }
    s = Search(using=client, index='flyertea', doc_type='thread')\
        .from_dict(body)
  

File "Search.py", line 26, in <module>
    print (s.execute())
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 598, in execute
    es = connections.get_connection(self._using)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/connections.py", line 94, in get_connection
    raise KeyError('There is no connection with alias %r.' % alias)
KeyError: "There is no connection with alias 'default'."

**Comment by HonzaKral** [comment]
`from_dict` is a class method that constructs a new `Search` object (which doesn't have your settings), if you want to use the current one with your settings use `update_from_dict`.

You can also use the `connections` object in the `connections` module of `elasticsearch_dsl` to configure the connection globally.

Hope this helps

**Comment by leoliuxd** [comment]
thanks

**Comment by LandonStewart** [comment]
Arrgggggg..... I actually knew this one but forgot about it.

**Comment by Divuzki** [comment]
i am confused

**Comment by GrudenOK** [comment]
good day. I receive the same error when i'm using opensearch_dsl
django_opensearch_dsl but everything the same with elasticsearch and I think maybe someone know whats going wrong)
# settings
OPENSEARCH_DSL = {
    "default" : {
        "scheme": "https",
        'hosts': 'opensearch:9200',
        'http_auth': ("admin", "admin"),
        'verify_certs': False,
    },
}

# document the same second
@registry.register_document
class FirstDocument(Document):

    class Index:
        name = "first"
        settings = {"number_of_shards": 1, "number_of_replicas": 0}

    class Django:
        model = First
        fields = ["first_name", "id", "last_name"]

    @classmethod
    def generate_search_query(cls, query):
       # just generate query
        return Q("match_all")

# view
 def list(self, request):
        query = request.query_params.get("q", "")
        category = request.query_params.get("category", [])
        if category and not "*":
            category = category.split(",")

        final_data = {}
        # when i'm add connection everthing works fine without receive an error
        # connections.create_connection(**settings.OPENSEARCH_DSL['default'])
        multi_search = MultiSearch()

        if settings.OPENSEARCH_INDEX["first"] in category:
            q = FirstDocument.generate_search_query(query)
            search = Search(index=settings.OPENSEARCH_INDEX["first"]).query(q)
            multi_search = multi_search.add(search)

        if settings.OPENSEARCH_INDEX["second"] in category:
            q = VehicleDocument.generate_search_query(query)
            search = Search(index=settings.OPENSEARCH_INDEX["second"]).query(q)
            multi_search = multi_search.add(search)

        responses = multi_search.execute() << here is an error

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/opensearch_dsl/connections.py", line 118, in get_connection
    return self.create_connection(alias, **self._kwargs[alias])
                                           ^^^^^^^^^^^^^^^^^^^
During handling of the above exception ('default'), another exception occurred:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/project/search/api/views/search.py", line 44, in list
    responses = multi_search.execute()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/opensearch_dsl/search.py", line 808, in execute
    opensearch = get_connection(self._using)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/opensearch_dsl/connections.py", line 121, in get_connection
    raise KeyError("There is no connection with alias %r." % alias)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: KeyError at /api/search/
Exception Value: "There is no connection with alias 'default'."

I took a look inside the library and it's take connection 'default' I also have that connection in settings where is my error. Thank you
