### ISSUE TITLE
u'security_exception', u'missing authentication token for REST request [/_nodes/_all/http]')

### ISSUE THREAD

**Issue by hello4usharath** [elastic/elasticsearch-dsl-py#765]
Traceback (most recent call last):
  File "create_mappings.py", line 40, in <module>
    sniffer_timeout=60
  File "C:\Python27\lib\site-packages\elasticsearch\client\__init__.py", line 171, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 122, in __init__
    self.sniff_hosts(True)
  File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 241, in sniff_hosts
    node_info = self._get_sniff_data(initial)
  File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 204, in _get_sniff_data
    timeout=self.sniff_timeout if not initial else None)
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "C:\Python27\lib\site-packages\elasticsearch\connection\base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, u'security_exception', u'missing authentication token for REST request [/_nodes/_all/http]')

**Comment by hello4usharath** [comment]
Getting above error after x-pack is enbled.

**Comment by WisdomPill** [comment]
Can you please post the code that gives you the error? Only the stack trace is not sufficient to find a bug or help you adjust your code.

**Comment by fxdgear** [comment]
@hello4usharath X-Pack by default requires authenticated access. 

most likely you need to instantiate your connection to Elasticsearch with a username and password http://elasticsearch-py.readthedocs.io/en/master/index.html?highlight=http_auth#ssl-and-authentication

by default before ES 6.0 that would be username: `elastic` and password `changeme`

if you continue to have issues please feel free to reopen and add additional information like what @WisdomPill asked for.
