### ISSUE TITLE
Question:  Is Elasticsearch-DSL compatible with Elasticsearch 6.0.0-rc2

### ISSUE THREAD

**Issue by hatdropper1977** [elastic/elasticsearch-dsl-py#767]
I tried to save a document to **_Elasticsearch 6.0.0-rc2_** using **_Elasticsearch-DSL 5.3.0_**.
 I can connect to my Elastic Cluster with no issues:
```python
>>> es = Elasticsearch(
... ELASTICSEARCH_ADDRESS,
...      http_auth = ( 'elastic' , ELASTICSEARCH_PASSWORD ),
... port = 9200,
... use_ssl = True,
... ca_certs = CA_CERT,
... )
>>> es.info()
{u'cluster_name': u'elk-fun', u'cluster_uuid': u'egi6MrOlRY6Yd9rFlgAc_w', u'version': {u'build_date': u'2017-10-29T08:46:09.697Z', u'minimum_wire_compatibility_version': u'
5.6.0', u'build_hash': u'119515d', u'number': u'6.0.0-rc2', u'minimum_index_compatibility_version': u'5.0.0', u'build_snapshot': False, u'lucene_version': u'7.0.1'}, u'name'
: u'ZgaHbjS', u'tagline': u'You Know, for Search'}
```
 I can then easily create an index with the mappings.
```python
>>> class TestDoc(DocType):
...         title = Text()
...         message = Text()
... 
>>> unittestindex = Index('unittestindex',es)
>>> unittestindex.delete(ignore=404)
{u'acknowledged': True}
>>> unittestindex.doc_type(TestDoc)
<class '__console__.TestDoc'>
>>> unittestindex.create()
>>> print unittestindex.get_mapping()
{u'unittestindex': {u'mappings': {u'test_doc': {u'properties': {u'message': {u'type': u'text'}, u'title': {u'type': u'text'}}}}}}
```
But when I try to save a Document, it fails.
```python
>>> testdoc = TestDoc(meta={'id':19},title='foo',message='Testing 123')
>>> testdoc.save(es)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    testdoc.save(es)
  File "/home/centos/pyscripts/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 418, in save
    return meta['created']
KeyError: 'created'
```
  Is Elasticsearch-DSL 5.3.0 compatible with the Elastic stack 6.0.0-rc2?

**Comment by tsouza** [comment]
It is not compatible. Any elasticsearch-dsl version "5.x.y" is compatible with Elasticsearch 5 only.
