### ISSUE TITLE
@property not working in DocType derived class?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#81]
I have the following class:

```
class TestUser(DocType, UserMixin):
    email = String(index="not_analyzed")
    pw_hash = String(index="not_analyzed")

    class Meta:
        index = "testing"
        doc_type = "test_users"

    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute.')

    @password.setter
    def password(self, password):
        self.pw_hash = generate_password_hash(password)
```

I therefore expect any call to the "password" attribute to raise an error, and any setting of it to set a pw_hash attribute...

However, this is what happens:

```
>>> test_user = TestUser(_id=1, email="test_user@test.com")
>>> test_user.save()
True
>>> test_user.to_dict()
{'email': 'test_user@test.com'}
>>> test_user.meta.to_dict()
{'id': '1', 'version': 1, 'index': 'testing'}
>>> test_user.password = "test"
>>> test_user.to_dict()
{'email': 'test_user@test.com', 'password': 'test'}

```

Am I doing something wrong here?

**Comment by HonzaKral** [comment]
No, you are not. This is an artefact of the way `AttrDict` is implemented (which `DocType` extends). It was described in #55 and I rejected the issue as too arcane and that it wouldn't be an issue.

I was wrong, apologies to @dourvaris.

Since this is not the first time (and we can safely assume not the last one) this has happened and we have a fix, let's fix it. Thanks for the report.

**Comment by njoannin** [comment]
Ah, yeah, sorry: I should have looked it up in previous issues before posting... I would have linked it to #55 from the start!

**Comment by njoannin** [comment]
Hmmm, I just read through #55 again...

The issue discussed in it does not seem to be quite the same. Or rather, it is the same, but I'm not sure the identified problem is quite the right one: it was all about raising the wrong type of error.

Lets look at this example again:

```
class TestUser(DocType): 
    email = String(index="not_analyzed")
    pw_hash = String(index="not_analyzed")
    class Meta:
        index = "testing"
        doc_type = "test_users"
    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute.')
    @password.setter
    def password(self, password):
        self.pw_hash = generate_password_hash(password)
```

And then:

```
>>> test_user = TestUser()
>>> test_user.password
Traceback (most recent call last):
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 103, in __getattr__
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/document.py", line 89, in __getattr__
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 399, in __getattr__
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 106, in __getattr__
AttributeError: 'TestUser' object has no attribute 'password'
```

And there is the ```AttributeError```. But not because of some mechanism that hides another type of error.

It is actually because ```@property``` is not doing its job:

```
>>> test_user.password = "test"
>>> test_user.password
'test'
```

To me it seems like the ```@property``` is completely ignored, which would be a BIG issue, even a deal breaker for me using elasticsearch-dsl-py. And I REALLY want to use it...

I had a look at the source code, but my limited knowledge of Python and programming in general are probably responsible for my total failure to see where such a problem could be coming from :(

**Comment by njoannin** [comment]
FYI, I tried using this form:

```
class TestUser(DocType): 
    email = String(index="not_analyzed")
    pw_hash = String(index="not_analyzed")
    class Meta:
        index = "testing"
        doc_type = "test_users"
    def get_password(self):
        raise AttributeError('Password is not a readable attribute.')
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
    password = property(get_password, set_password)
```

But it didn't work either.

**Comment by njoannin** [comment]
Workaround, until a better solution is found:

```
class TestUser(DocType): 
    email = String(index="not_analyzed")
    pw_hash = String(index="not_analyzed")
    pw_sdt = Date()

    class Meta:
        index = "testing"
        doc_type = "test_users"

    def __getattr__(self, name):
        if name == "password":
            raise AttributeError('Password is not a readable attribute.')
        return super(DocType, self).__getattr__(name)

    def __setattr__(self, name, value):
        if name == "password":
            self.pw_hash = generate_password_hash(value)
            self.pw_sdt = datetime.utcnow()
            return
        return super(DocType, self).__setattr__(name, value)

    #@property
    #def password(self):
    #    raise AttributeError('Password is not a readable attribute.')
    #@password.setter
    #def password(self, password):
    #    self.pw_hash = generate_password_hash(password)
```

This works for me:

```
>>> test_user = TestUser(email="test@email.com")
>>> test_user.save()
True
>>> test_user.password = "test"
>>> test_user.password
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 13, in __getattr__
AttributeError: Password is not a readable attribute.
>>> test_user.to_dict()
{'email': 'test@email.com', 'pw_sdt': datetime.datetime(2015, 3, 3, 12, 12, 53, 89441), 'pw_hash': 'pbkdf2:sha1:1000$SILlHbKs$91bb4f2094c3e968fb57538f491aa5e53e135258'}
```

Any suggestion of other/better solutions are most welcome!

**Comment by njoannin** [comment]
Thanks for the fix!

**Comment by wanthalf** [comment]
I have this problem again when using multiple inheritance. It works if @property is defined directly in the body of the object (as the last examples show here), but if it is defined and inherited from a Mixin class (aka the "UserMixin" in the example of the first post of this thread), I get problems again. (Actually they seem to behave strangely and unpredictably, especially within InnerDocs.)
