### ISSUE TITLE
Odd behaviour of Nested type fields vs other types

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#83]
I expect an attribute that is not set to raise an error (preferably an AttributeError) when it is called directly, e.g. ```
my_instance.some_attribute```
...

However, with the following class:

```
class TestUser(DocType): 
    email = String(index="not_analyzed")
    friends = Nested(properties={
                        "email": String(index="not_analyzed"),
                        "name": String()
    })
    class Meta:
        index = "testing"
        doc_type = "test_users"
```

If I instantiate, without setting any attribute, and then call each attribute I get a surprising result:

```
>>> test_user = TestUser()
>>> test_user.to_dict()
{}
>>> test_user.friends
[]
>>> test_user.email
Traceback (most recent call last):
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 103, in __getattr__
KeyError: 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/document.py", line 89, in __getattr__
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 399, in __getattr__
  File "/Users/Nicolas/my_project/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 106, in __getattr__
AttributeError: 'TestUser' object has no attribute 'email'
>>> test_user.to_dict()
{'friends': []}
```

Is this the expected behaviour?

**Comment by HonzaKral** [comment]
Yes, this is an expected behavior (though I have failed in documenting it so far). The rationale here is that nested will always be a list so people should be able to just `.append` to it if they want to add a nested document.

It occurs to me now that we should expose (and document!) this for other fields as well, perhaps by exposing `multiple=False` option for all fields - if set to `True` (which will be the default for nested) then this behavior will manifest.

Does that make sense to you?

Thanks!

**Comment by njoannin** [comment]
OK...

Yes, I do think that it would be better to have it as an option, as it is a bit counter intuitive to the expected Python behaviour (I think, please correct me if I'm mistaken)...

Also, having it as an option for all types of fields would make it consistent across the range of Fields, and being able to do that is kind of neat too :)
