### ISSUE TITLE
TypeError when serializing object including InnerDoc created using DocType

### ISSUE THREAD

**Issue by OskarPersson** [elastic/elasticsearch-dsl-py#837]
I have setup the following DocType:

```
class InnerTestDoc(InnerDoc):
    inner_field = Keyword()

class TestDoc(DocType):
    inner = Object(InnerTestDoc)
    class Meta:
        index = 'testdoc'
```

When I create a new document using `DocType` with a given index and try to serialize the result to json I get a `TypeError`. If I instead create the same document using `TestDoc` I can serialize it without errors:

```
>>> import json
>>> from elasticsearch_dsl import DocType
>>> from documents import TestDoc, TestInnerDoc

>>> TestDoc.init()
>>> inner = TestInnerDoc(inner_field="myinnerfield")
>>> t1 = DocType(_index='testdoc', inner=inner)
>>> t1.save()
True
>>> json.dumps(t1.to_dict())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Oskar/.pyenv/versions/2.7.13/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Users/Oskar/.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/Oskar/.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/Oskar/.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {'inner_field': 'foo'} is not JSON serializable

>>> t2 = TestDoc(inner=inner)
>>> t2.save()
>>> json.dumps(t2.to_dict())
'{"inner": {"name": "foo"}}'
```

---

Environment:

```
$ pip freezer | grep elasticsearch
elasticsearch==6.1.1
elasticsearch-dsl==6.1.0

$ elasticsearch --version
Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_60
```

**Comment by HonzaKral** [comment]
Yes, `DocType` doesn't have all the information required to properly serialize the `InnerDoc` objects since it doesn't have the field defined on it. `.save()` works because it uses the serializer defined in https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/serializer.py which looks for `to_dict` methods on any values.

i am sorry for the confusion, but this is not expected to work. What do you think we can do to make this clearer for users?

Thank you for the report!

**Comment by HonzaKral** [comment]
Closing this since using `DocType` directly is unsupported and undocumented, you should always subclass.
