### ISSUE TITLE
Properly support for percolator in query

### ISSUE THREAD

**Issue by SalahAdDin** [elastic/elasticsearch-dsl-py#866]
I get this error when i want use a percolator in a query search:
```
>>> s = Search().using(client).query("percolate", field=text).highlight('title')
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/Works/seminer/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 214, in get_dsl_class
    return cls._classes[name]
KeyError: 'percolate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salahaddin/Proyectos/Works/seminer/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 33, in __call__
    getattr(s, self._attr_name)._proxied &= Q(*args, **kwargs)
  File "/home/salahaddin/Proyectos/Works/seminer/lib/python3.6/site-packages/elasticsearch_dsl/query.py", line 31, in Q
    return Query.get_dsl_class(name_or_query)(**params)
  File "/home/salahaddin/Proyectos/Works/seminer/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 216, in get_dsl_class
    raise UnknownDslObject('DSL class `%s` does not exist in %s.' % (name, cls._type_name))
elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `percolate` does not exist in query.
```

**Comment by SalahAdDin** [comment]
Initial with this: https://github.com/elastic/elasticsearch-dsl-py/pull/867
