### ISSUE TITLE
Nested Field Gives TypeError upon indexing.

### ISSUE THREAD

**Issue by prabin525** [elastic/elasticsearch-dsl-py#874]
Whenever i try to save an object that has a nested field i get a Type error.

`TypeError: isinstance() arg 2 must be a type or tuple of types`

I have following document classes: 

	class CreationIndex(InnerDoc):

		created_by = Keyword()
		created_date = Date()

	class UpdationIndex(InnerDoc):

		updated_by = Keyword()
		updated_date = Date()

	class IndustryIndex(DocType):
		name = Text(analyzer= 'english')
		creation = CreationIndex()
		updation = Nested(UpdationIndex())

		class Meta:
			index = 'industry'
	def bulk_indexing():

		elastic_connection = Elasticsearch(hosts=['localhost'], timeout=20)
		if elastic_connection.indices.exists('industry'):
			elastic_connection.indices.delete('industry')
		if elastic_connection.indices.exists('category'):
			elastic_connection.indices.delete('category')

		IndustryIndex.init()
		print('HI')
		bulk(client=elastic_connection, actions=(b.indexing() for b in models.Industry.objects.all()))

My Industry Model is a django model (where i have used mongoDB so itself is a dynamic document) which is defined as

	class Industry(DynamicDocument,BaseCreationUpdation):
		name=StringField(required=True,unique=True)

		def save(self,*args,**kwargs):
			'''
			'''
			self=save_created_updated_info(self)
			super(Industry,self).save(args,kwargs)

		def indexing(self):
			objCreation = CreationIndex(
				created_by = self.creation.created_by,
				created_date = self.creation.created_date.date().isoformat()
				)
			print(objCreation.to_dict())
			obj = IndustryIndex(
				meta = {'id': str(self.id)},
				name = self.name,
				creation = objCreation.to_dict(),
				updation = [],
				)
			
			for objUp in self.updation:
				
				objUpdation = UpdationIndex(
					updated_by = objUp.updated_by,
					updated_date = objUp.updated_date.date().isoformat()
					)
				print(objUpdation)
				obj.updation.append(objUpdation)
				print()
				print(obj.to_dict())
				print()
			obj.save()
			
			return obj.to_dict(include_meta=True)

		@classmethod
		def index_document(cls,sender, document, **kwargs):
			document.indexing()

Now whenever i run the bulk_indexing module it comes up with a problem : 

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\projects\django\bhetincha\category\search.py", line 57, in bulk_indexing
    bulk(client=elastic_connection, actions=(b.indexing() for b in models.Industry.objects.all()))
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch\helpers\__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch\helpers\__init__.py", line 180, in streaming_bulk
    client.transport.serializer):
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch\helpers\__init__.py", line 58, in _chunk_actions
    for action, data in actions:
  File "D:\projects\django\bhetincha\category\search.py", line 57, in <genexpr>
    bulk(client=elastic_connection, actions=(b.indexing() for b in models.Industry.objects.all()))
  File "D:\projects\django\bhetincha\category\models.py", line 80, in indexing
    obj.save()
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\document.py", line 405, in save
    self.full_clean()
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\utils.py", line 417, in full_clean
    self.clean_fields()
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\utils.py", line 403, in clean_fields
    data = field.clean(data)
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\field.py", line 179, in clean
    data = super(Object, self).clean(data)
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\field.py", line 90, in clean
    data = self.deserialize(data)
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\field.py", line 81, in deserialize
    for d in data
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\field.py", line 81, in <listcomp>
    for d in data
  File "C:\Users\prabi\Envs\bhetincha\lib\site-packages\elasticsearch_dsl\field.py", line 160, in _deserialize
    if isinstance(data, self._doc_class):
TypeError: isinstance() arg 2 must be a type or tuple of types`

Why is there this error? When i removed the updation filed which is nested it all works, though the creation field is the same. Whats the problem here?

**Comment by HonzaKral** [comment]
The only thing I can see right away is that `creation` should be defined as `creation = Object(CreationIndex())` insetad of just `creation = CreationIndex()`. You also don't need to explicitly serialize your dates, the library will do it for you.

Other than that I don't see a large issue, can you please double check that it's updation and not creation causing the issue? I will try and replicate this issue later.

Thanks!

**Comment by prabin525** [comment]
Thank you very much for your quick reply.

When i defined `creation = CreationIndex()` the mapping was wrong, it gave creation as `type = text` but it was working. But now when i changed to `creation = Object(CreationIndex())` , I am getting the same error as i was getting in `updation`. `  if isinstance(data, self._doc_class):
TypeError: isinstance() arg 2 must be a type or tuple of types`.

**Comment by prabin525** [comment]
I was able to make it work by a simple change in the way i defined the doc.

`class IndustryIndex(DocType):
	name = Text(analyzer= 'english')
	creation = Object(CreationIndex)
	updation = Nested(UpdationIndex)

	class Meta:
		index = 'industry'`

This worked for me fine.
