### ISSUE TITLE
Feature request: make DocType obj.get("unkown_id") return None

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#88]
Currently, if we try to get a document with an unknown id, a NotFoundError (TransportError) is raised.

This means that in many cases, a simple get(id) should be handled with a ```try:... except:...```:
 
```
>>> tu=TestUser.get("test")
GET /testing/test_users/test [status:404 request:0.002s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/document.py", line 115, in get
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch/client/__init__.py", line 322, in get
    params=params)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch/connection/http_urllib3.py", line 82, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch/connection/base.py", line 102, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"testing","_type":"test_users","_id":"test","found":false}')
>>> 
>>> try:
...     tu = TestUser.get("test")
... except TransportError:
...     tu = None
... 
GET /testing/test_users/test [status:404 request:0.002s]
>>> tu
>>> 
```

I was wondering if it might be better to have it return None instead, in which case the above ```try:... except:...```
 would become:

```
>>> tu = TestUser.get("test")
>>> tu is None
True
```

What are your thoughts on this suggestion?

**Comment by HonzaKral** [comment]
I am not sure this is what people expect - in other DB systems like Django ORM `.get` on a non-existent object will raise an exception. What we could perhaps do it add a `get_or_none` method (really not happy with that name) a parameter to `get` that would make it behave like that.

What do you, and other people, think?

**Comment by njoannin** [comment]
That would be great, to add a method for that. If not the sexiest name for a method, ```get_or_none``` is at least explicit and to the point. I'm OK with it.
Thanks for offering an alternative!

**Comment by jaddison** [comment]
Personal preference speaking, but I'd prefer not to pollute the class with additional use cases. Provide the basics first and foremost.

Going with the django example, it might be better to have utility functions like get_object_or_404() and get_object_or_None().

OK, probably not the 404 one, as that's framework specific.
