### ISSUE TITLE
Bulk Operation times out, raises socket.timeout and ReadTimeoutError

### ISSUE THREAD

**Issue by mweinelt** [elastic/elasticsearch-dsl-py#901]
I'm doing bulk updates on an index and that sometimes times out. I'm then trying to handle the `socket.timeout` exception, but during the except clause the `urllib3.exceptions.ReadTimeoutError` is raised, so that my exception handling doesn't happen.

Code looks like this:
```python
    def commit(self):
        try:
            success, errors = bulk(self.es, self.queue)
            self.queue.clear()
        except socket.timeout:
            # exponential backoff logic
```

I'm unclear how to handle the `ReadTimeoutError`:

```pytb
WARNING:elasticsearch:POST http://192.168.200.8:9200/_bulk [status:N/A request:10.009s]
Traceback (most recent call last):
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hexa/.local/share/virtualenvs/scrape-tracker-j7-pHtJR/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.200.8', port=9200): Read timed out. (read timeout=10)
WARNING:elasticsearch:Connection <Urllib3HttpConnection: http://192.168.200.8:9200> has failed for 1 times in a row, putting on 60 second timeout.
```

Help is appreciated!

**Comment by HonzaKral** [comment]
Hi, these exceptions should all be wrapped in `elasticsearch.ConnectionTimeout` (0). You should only need to catch that or its parent - `ConnectionError`. If that is not the case and you are seeing the `urllib3` exception then that is a bug in the underlying `elasticsearch-py` library (1) and should be reported there.

Btw if you are getting timeouts try raising the timeout by passing in `request_timeout` to the `bulk` call set to a higher value. Alternatively try lowering your `chunk_size` from the default `500` to make smaller chunks that will be processed quicker.

Hope this helps!

0 - http://elasticsearch-py.readthedocs.io/en/master/exceptions.html#elasticsearch.ConnectionTimeout
1 - https://github.com/elastic/elasticsearch-py
