### ISSUE TITLE
How to write multiple match_phrase queries for a "should"

### ISSUE THREAD

**Issue by WolfangAukang** [elastic/elasticsearch-dsl-py#925]
Hi guys, this is a question. I am testing your library and I need to put multiple match_phrase for a bool query, as shown below:
```
{
  "query" : {
    "bool": {
      "filter": {
        "range": {
          "@timestamp": {
            "gte": "now-5m"
          }
        }
      },
      "should": [
        {
          "match_phrase": {
            "entry.action": "act1"
          }
        },
        {
          "match_phrase": {
            "entry.action": "act2"
          }
        },
         ...
      ],
      "minimum_should_match": 1
    }
  }
}
```

So, this is what I have tried so far, with no luck:
```
q = Q('bool',
       should=[Q("match_phrase", fields=['entry.action'], query="act1"),
                      Q("match_phrase", fields=['entry.action'], query="act2")  ],
       minimum_should_match=1
)
s = Search(using=es, index="test-*").filter('range', **{'@timestamp': {'gte': 'now-24h'}}).query(q)

response = s.execute()
```
Error message is:
```
GET https://server.com:9200/test-*/_search [status:500 request:0.417s]
Traceback (most recent call last):
  File "./elasticsearch_python.py", line 81, in <module>
    main()
  File "./elasticsearch_python.py", line 79, in main
    nueva(client)
  File "./elasticsearch_python.py", line 73, in nueva
    response = s.execute()
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 679, in execute
    **self._params
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, 'illegal_state_exception', "Can't get text on a START_ARRAY at 1:109")
```
If I run it with only the filter, without the query part (q), I get the results normally.

**Comment by HonzaKral** [comment]
`match_phrase` query doesn't support `fields` parameter, you need the kwargs to the `Q` helper be exactly the same as what you have inside the json. The only exception is for fields with `.` where you can replace the `.` with `__`,  so:
```python
{
  "match_phrase": {
    "entry.action": "act1"
  }
}
```
becomes
```python
Q('match_phrase', entry__action="act1")
```

hope this helps

**Comment by WolfangAukang** [comment]
Perfect, worked as expected. The double underscore was also helpful. Thank you, Honza.
