### ISSUE TITLE
Unable to use Mapping with Document

### ISSUE THREAD

**Issue by pigletto** [elastic/elasticsearch-dsl-py#940]
elasticsearch_dsl 6.2.1

```
>>> from elasticsearch_dsl import Document, Mapping
>>> tm = Mapping('blah')
>>> class TestDocument(Document):
...     class Meta:
...         mapping = tm
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pigletto/.virtualenvs/elasticdsl/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 32, in __new__
    new_cls._index.document(new_cls)
  File "/home/pigletto/.virtualenvs/elasticdsl/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 123, in document
    'trying to assign %s.' % (self._mapping.doc_type, name))
elasticsearch_dsl.exceptions.IllegalOperation: Index object cannot have multiple types, doc already set, trying to assign blah.
```

**Comment by HonzaKral** [comment]
To do this you also have to define the `doc_type` on `class Meta` to the same name (`blah`) for it to work. Sorry for the inconvenience

**Comment by HonzaKral** [comment]
I meant:
```python
class D(Document):
    class Meta:
        mapping = Mapping('blah')

    class Index:
        doc_type = 'blah'
```
