### ISSUE TITLE
Index.document bug

### ISSUE THREAD

**Issue by tstallings** [elastic/elasticsearch-dsl-py#941]
Issue
===

Calls to an `Index` instance's `document()` function fail to add multiple document types to an index. I see things have been changing around this so I was curious if this is expected behavior that isn't reflected in the docs yet, or if this was a bug that was accidentally introduced. I ask because this used to work, but I could have been doing it wrong :P

Example script
===

```python
from datetime import datetime
from elasticsearch_dsl import (
    connections,
    Date,
    DocType,
    Float,
    Index,
    Integer,
    Ip,
    Keyword,
    Text
)
from elasticsearch import Elasticsearch
import argparse
import json
import logging

logging.basicConfig(level=logging.DEBUG)
LoggingIndex = Index("tmp")


class GenericDoc(DocType):

    timestamp = Date()
    size = Integer()
    version = Keyword()
    delayed_by = Float()
    indexed_at = Date()
    ignored = Text(index=False)

    def save(self, **kwargs):
        self.indexed_at = datetime.now()
        return super(GenericDoc, self).save(**kwargs)


@LoggingIndex.doc_type
class EventDoc(GenericDoc):

    class Meta:
        doc_type = "some_doc"

    Username = Text()
    IP_Address = Ip()
    Data = Text()
    Action = Keyword()


@LoggingIndex.doc_type
class DetailDoc(GenericDoc):

    class Meta:
        doc_type = "other_doc"

    Username = Text()
    Status = Keyword()
    Data = Text()
    Action = Keyword()


def main(args):

    log = logging.getLogger("main")
    log.info("Connecting to ES")
    es = Elasticsearch(args.es)
    connections.add_connection('default', es)

    log.info("Creating index settings")
    if not LoggingIndex.exists():
        LoggingIndex.create()

    log.info("Creating test event")
    test_event = {
        'Username': 'username',
        'Action': 'did a thing',
        'IP_Address': '1.1.1.1',
        'Data': 'Event details here',
        'Time': '2018-06-29 15:45:29'
    }
    doc = EventDoc(**test_event)
    print json.dumps(doc.to_dict(), indent=4)


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-es",
        action="store",
        default="localhost",
        required=False,
        help="Specify the elasticsearch host"
    )

    args = parser.parse_args()
    main(args)
```

Expected Output
===

```bash
>>> python example_script.py
INFO:main:Connecting to ES
INFO:main:Creating index settings
DEBUG:urllib3.util.retry:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9200
DEBUG:urllib3.connectionpool:http://localhost:9200 "HEAD /tmp HTTP/1.1" 200 0
INFO:elasticsearch:HEAD http://localhost:9200/tmp [status:200 request:0.007s]
DEBUG:elasticsearch:> None
DEBUG:elasticsearch:<
INFO:main:Creating test event
{
    "Username": "username",
    "Action": "did a thing",
    "IP_Address": "1.1.1.1",
    "Data": "Event details here",
    "Time": "2018-06-29 15:45:29"
}
>>>
>>> pip freeze | grep dsl 
>>> elasticsearch-dsl==6.1.0
```

Actual Output
===

```
>>> python example_script.py
Traceback (most recent call last):
  File "test_simple.py", line 37, in <module>
    class SomeDoc(GenericDoc):
  File "/Users/tstallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 32, in __new__
    new_cls._index.document(new_cls)
  File "/Users/tstallings/.virtualenvs/dev/lib/python2.7/site-packages/elasticsearch_dsl/index.py", line 123, in document
    'trying to assign %s.' % (self._mapping.doc_type, name))
elasticsearch_dsl.exceptions.IllegalOperation: Index object cannot have multiple types, doc already set, trying to assign some_doc.
>>>
>>> pip freeze | grep dsl
>>> elasticsearch-dsl==6.2.1
```

**Comment by HonzaKral** [comment]
Multiple doc types in a single index are not supported by elasticsearch 6.x.

If you want to set the name of your mapping you also need to specify both `class Meta` and `class Index` as specified in #940

**Comment by HonzaKral** [comment]
If you want to have multiple Document classes stored in a single index still, you can see the parent_child.py example in the `examoles` directory on how to simulate multiple doc types from python.
