### ISSUE TITLE
DocType with None value in Date field is broken

### ISSUE THREAD

**Issue by btx** [elastic/elasticsearch-dsl-py#97]
Hi, 

I've got problems with storing None value to Date field.

```
class Document(DocType):
    updated_at = Date()
```

Then, when `updated_at` field of the retrieved document is empty, I get:
```
Document.get(id='docid1)

...

AttributeError: 'NoneType' object has no attribute 'read'
```

I've attempted to fix it and it looks like the following works for me: https://github.com/btx/elasticsearch-dsl-py/commit/c5394ad388e2f5558980cbf7110fa2bfc99b6e95 (fixed test: https://github.com/btx/elasticsearch-dsl-py/commit/b34a32c23bdcff910a179726130a6a3308484b36).

Is that a correct fix?
Thanks

**Comment by njoannin** [comment]
That's odd, in my testing with your example, everything seems to work fine:

```
>>> es.indices.create("test_index")
{'acknowledged': True}
>>> from elasticsearch_dsl import DocType, Date
>>> class Document(DocType):
...    updated_at=Date()
...    class Meta:
...       index="test_index"
... 
>>> d=Document(_id="docid1")
>>> d.save()
True
>>> d=Document.get(id="docid1")
>>> d
{}
>>> d.meta.to_dict()
{'version': 1, 'index': 'test_index', 'doc_type': 'document', 'id': 'docid1', 'found': True}
```

Could you add more details, e.g. the full testing you've done to isolate the issue and/or the complete error stack trace?

**Comment by njoannin** [comment]
Ah, I found your error:

```
>>> d.updated_at=None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/document.py", line 94, in __setattr__
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 410, in __setattr__
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/field.py", line 49, in to_python
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/field.py", line 118, in _to_python
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 300, in parse
    res = self._parse(timestr, **kwargs)
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 358, in _parse
    l = _timelex.split(timestr)
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 139, in split
    return list(cls(s))
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 130, in __next__
    token = self.get_token()
  File "/Users/Nicolas/Dropbox/Perso/Websites/LabFreeze/labfreeze_v2/flask/lib/python3.3/site-packages/dateutil/parser.py", line 61, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'
>>> d.updated_at=None
```

But if your attribute is set to be a Date object, why would you want to make it a NoneType?
I think that in a relational model it makes sense, but in a NoSQL model it doesn't: if an attribute is empty, you just don't set it.

**Comment by btx** [comment]
Oh, I see now, thanks. Coming from a relational world I did not think of that.
I'm bulk-indexing (using python elasticsearch client), so I suppose I should check for empty attributes and not set them at all.

**Comment by njoannin** [comment]
@btx That would be my best guess. That said, maybe others will suggest different options.

**Comment by HonzaKral** [comment]
I agree with @njoannin - don't set the attribute.

We could make this explicit and actually remove an attribute when it's being set to `None` too, but I would much rather avoid that.

For now what I think a proper solution to this is to create a custom exception and don't just raise any underlying error like in this occasion.

**Comment by btx** [comment]
Thanks, @HonzaKral.

In my use case I have lots of documents which have random attributes filled with an empty value. I'd like to access documents conveniently (in Django models fashion) regardless of their attributes' values. I'd like to avoid the necessity of checking if an attribute exists or using `getattr`.

It would simply return `None` if:

* 1) an attribute is set to empty value
* 2) an attribute is not set (indexed) at all but is defined in the corresponding mapping.

In order to make it work also `Date` field have to be modified.

In your opinion, what would be the best approach?
