### ISSUE TITLE
Cannot assign a Nested field attribute from an existing instance

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#99]
Hmm, I'm not sure that title is very clear :( Best to go through an example...

Example:

Here's the class:

```
>>> class TestUser(DocType): 
...     email = String(index="not_analyzed")
...     friends = Nested(properties={
...                         "email": String(index="not_analyzed"),
...                         "name": String()
...     })
...     class Meta:
...         index = "testing"
...         doc_type = "test_users"
... 
>>> TestUser.init()
```

Create a first instance of that class:

```
>>> t1 = TestUser(email="test@email.com", friends=[{"email":"other@email.com", "name":"Bob"}], _id=1)
>>> t1.save()
True
```

No problem. But now, create a new instance, without setting any attribute.
Then, assign attributes, using the attributes set to the first instance:

```
>>> t2 = TestUser()
>>> t2.email = t1.email
>>> t2
{'email': 'test@email.com'}
```

The ```
String```
 field works fine. But, not the ```Nested```
 field:

```
>>> t2.friends = t1.friends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/document.py", line 94, in __setattr__
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 410, in __setattr__
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/field.py", line 49, in to_python
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/field.py", line 98, in _to_python
TypeError: type object argument after ** must be a mapping, not AttrList
```

I'm guessing this is a bug? Any suggestion for a workaround until it is fixed?

**Comment by HonzaKral** [comment]
Thanks for the report, it was a regression that happened when we changed `AttrList` to no longer extend `list`

**Comment by njoannin** [comment]
Thanks for fixing it!
